### PR TITLE
Finished week_2

### PR DESCRIPTION
**Pull request by alice1315**
黃允謙

http://52.205.16.106:3000/

### CODE REVIEW

**Comment by alice1315** [comment]
Found another error,  will reopen after fixing it.

**Comment by alice1315** [comment]
Fixed errors in infinite scroll(fetching duplicate pages).

**Comment by alice1315** [comment]
黃允謙

http://52.205.16.106:3000/

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
